name: surf_practice_magic_ball
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: 3.0.6 # Dart SDK version
  flutter: 3.10.3 # Flutter SDK version

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

# getting data from api
  dio: ^5.3.0
  pretty_dio_logger: ^1.3.1
  json_annotation: ^4.8.1

# request when shaking
  shake: ^2.2.0

# core
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

# image caching
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

# generators
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true

  fonts:
    - family: Lumanosimo
      fonts:
        - asset: assets/fonts/Lumanosimo-Regular.ttf
